### ISSUE TITLE
Address OSError due to unclosed files

### ISSUE THREAD

**Issue by DrLynch** [ArgLab/writing_observer#2]
There exists a basic OSError due to unclosed socket connection.  This is reported in the ETS branck #17

https://github.com/ETS-Next-Gen/writing_observer/issues/17

**Comment by DrLynch** [comment]
Having found the source:

1) Push minimal fix that closes novel files at the end of method.
2) Identify sources of calls to novel file construction and explain.
3) Identify source of files list to determine how those are managed/extended.

**Comment by BenBeehler** [comment]
1) Minimal fix pushed in #13

**Comment by DrLynch** [comment]
TODO:  Examing file limit see stackoverflow why-python-has-limitfor count of file handles.  

Also need to examine content of files to determine why multiple triggered on login.  

NOTE: One issue may be that this is down to the plugin trying to reconnect on errors and on trying to connect on startup.  It may be failing to connect to the server and following that it generates meaningless traffic.  @BenBeehler take a look at this.

**Comment by DrLynch** [comment]
This error appears to have reappeared now that we are collecting larger datasets.  This should be updated to handle the expected load which means including some form of file pointer rotation.  Our current plan to manually reset daily just won't cut it.

**Comment by bradley-erickson** [comment]
This has been fixed with the implementation of closing websocket logs.
